const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
  VerticalAlign, LevelFormat, PageNumber, Header, Footer
} = require('docx');
const fs = require('fs');

const C = {
  erasmusBlue: '003DA5', erasmusYellow: 'FFD700', darkBlue: '0D1B3E',
  medBlue: '1A56DB', lightBlue: 'E8F0FE', green: '0EA371', lightGreen: 'E6F7F1',
  orange: 'F59E0B', lightOrange: 'FEF3CD', red: 'EF4444', lightRed: 'FEE2E2',
  purple: '8B5CF6', lightPurple: 'EDE9FE', gray: '5A6A8A', lightGray: 'F5F6FA',
  border: 'E2E8F5', white: 'FFFFFF',
};

const bdr = (c = C.border) => ({ style: BorderStyle.SINGLE, size: 1, color: c });
const borders = (c = C.border) => ({ top: bdr(c), bottom: bdr(c), left: bdr(c), right: bdr(c) });
const noBorder = () => ({ top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.NONE }, left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE } });

function cell(text, { fill=C.white, bold=false, color=C.darkBlue, size=18, align=AlignmentType.LEFT, width=2000, colSpan, italic=false }={}) {
  return new TableCell({
    columnSpan: colSpan,
    width: { size: width, type: WidthType.DXA },
    shading: { fill, type: ShadingType.CLEAR },
    borders: borders(C.border),
    margins: { top: 80, bottom: 80, left: 120, right: 120 },
    verticalAlign: VerticalAlign.CENTER,
    children: [new Paragraph({ alignment: align, children: [new TextRun({ text, bold, color, size, italics: italic, font: 'Arial' })] })]
  });
}

function h1(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 480, after: 160 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 8, color: C.erasmusBlue, space: 4 } },
    children: [new TextRun({ text, bold: true, color: C.erasmusBlue, size: 36, font: 'Arial' })]
  });
}
function h2(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 320, after: 120 },
    children: [new TextRun({ text, bold: true, color: C.darkBlue, size: 28, font: 'Arial' })]
  });
}
function h3(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_3,
    spacing: { before: 240, after: 80 },
    children: [new TextRun({ text, bold: true, color: C.medBlue, size: 24, font: 'Arial' })]
  });
}
function p(text, { color=C.darkBlue, size=20, bold=false, italic=false, spacing={ after: 120 }, indent }={}) {
  return new Paragraph({ spacing, indent, children: [new TextRun({ text, color, size, bold, italics: italic, font: 'Arial' })] });
}
function bl(text, { level=0, color=C.darkBlue, size=20, bold=false }={}) {
  return new Paragraph({ numbering: { reference: 'bullets', level }, spacing: { after: 60 }, children: [new TextRun({ text, color, size, bold, font: 'Arial' })] });
}
function nb(text, { level=0, color=C.darkBlue, size=20, bold=false }={}) {
  return new Paragraph({ numbering: { reference: 'numbers', level }, spacing: { after: 80 }, children: [new TextRun({ text, color, size, bold, font: 'Arial' })] });
}
function sp(n=1) { return Array.from({ length: n }, () => new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text: '', font: 'Arial' })] })); }
function divider(color=C.border) {
  return new Paragraph({ spacing: { before: 160, after: 160 }, border: { bottom: { style: BorderStyle.SINGLE, size: 2, color, space: 1 } }, children: [new TextRun({ text: '', font: 'Arial' })] });
}
function pageBreak() { return new Paragraph({ pageBreakBefore: true, children: [new TextRun('')] }); }

function infoBox(lines, { fill=C.lightBlue, borderColor=C.medBlue, labelColor=C.erasmusBlue }={}) {
  return new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [2200, 7160],
    borders: { top: { style: BorderStyle.SINGLE, size: 6, color: borderColor }, bottom: bdr(borderColor), left: bdr(borderColor), right: bdr(borderColor), insideH: { style: BorderStyle.NONE }, insideV: { style: BorderStyle.NONE } },
    rows: lines.map(([label, value]) => new TableRow({ children: [
      new TableCell({ width: { size: 2200, type: WidthType.DXA }, shading: { fill, type: ShadingType.CLEAR }, borders: noBorder(), margins: { top: 80, bottom: 60, left: 140, right: 80 }, children: [new Paragraph({ children: [new TextRun({ text: label, bold: true, size: 18, color: labelColor, font: 'Arial' })] })] }),
      new TableCell({ width: { size: 7160, type: WidthType.DXA }, shading: { fill, type: ShadingType.CLEAR }, borders: noBorder(), margins: { top: 80, bottom: 60, left: 80, right: 80 }, children: [new Paragraph({ children: [new TextRun({ text: value, size: 18, color: C.darkBlue, font: 'Arial' })] })] })
    ]}))
  });
}

function scoreTable(scores) {
  return new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [2800, 1200, 5360],
    rows: [
      new TableRow({ tableHeader: true, children: [cell('Dimension', { fill: C.erasmusBlue, bold: true, color: C.white, size: 18, width: 2800 }), cell('Score', { fill: C.erasmusBlue, bold: true, color: C.white, size: 18, width: 1200, align: AlignmentType.CENTER }), cell('Assessment', { fill: C.erasmusBlue, bold: true, color: C.white, size: 18, width: 5360 })] }),
      ...scores.map(([dim, score, note, fc]) => new TableRow({ children: [cell(dim, { fill: C.lightGray, bold: true, size: 18, width: 2800 }), cell(score, { fill: fc||C.lightBlue, bold: true, color: C.erasmusBlue, size: 18, width: 1200, align: AlignmentType.CENTER }), cell(note, { fill: C.white, size: 18, width: 5360 })] }))
    ]
  });
}

function twoCol(rows, headers) {
  const w = [3000, 6360];
  const hRow = headers ? new TableRow({ tableHeader: true, children: headers.map((h, i) => cell(h, { fill: C.erasmusBlue, bold: true, color: C.white, size: 17, width: w[i] })) }) : null;
  const dRows = rows.map((r, ri) => new TableRow({ children: r.map((t, i) => cell(String(t), { fill: ri%2===0?C.white:C.lightGray, size: 17, bold: i===0, color: i===0?C.darkBlue:C.gray, width: w[i] })) }));
  return new Table({ width: { size: 9360, type: WidthType.DXA }, columnWidths: w, rows: hRow ? [hRow, ...dRows] : dRows });
}

function threeCol(rows, headers, widths=[3000, 2000, 4360]) {
  const hRow = headers ? new TableRow({ tableHeader: true, children: headers.map((h, i) => cell(h, { fill: C.erasmusBlue, bold: true, color: C.white, size: 17, width: widths[i] })) }) : null;
  const dRows = rows.map((r, ri) => new TableRow({ children: r.map((t, i) => cell(String(t), { fill: ri%2===0?C.white:C.lightGray, size: 17, bold: i===0, color: i===0?C.darkBlue:C.gray, width: widths[i] })) }));
  return new Table({ width: { size: 9360, type: WidthType.DXA }, columnWidths: widths, rows: hRow ? [hRow, ...dRows] : dRows });
}

const doc = new Document({
  numbering: {
    config: [
      { reference: 'bullets', levels: [{ level: 0, format: LevelFormat.BULLET, text: '\u2022', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }, { level: 1, format: LevelFormat.BULLET, text: '\u25E6', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 1080, hanging: 360 } } } }] },
      { reference: 'numbers', levels: [{ level: 0, format: LevelFormat.DECIMAL, text: '%1.', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
    ]
  },
  styles: {
    default: { document: { run: { font: 'Arial', size: 20 } } },
    paragraphStyles: [
      { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 36, bold: true, font: 'Arial', color: C.erasmusBlue }, paragraph: { spacing: { before: 480, after: 160 }, outlineLevel: 0 } },
      { id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 28, bold: true, font: 'Arial', color: C.darkBlue }, paragraph: { spacing: { before: 320, after: 120 }, outlineLevel: 1 } },
      { id: 'Heading3', name: 'Heading 3', basedOn: 'Normal', next: 'Normal', quickFormat: true, run: { size: 24, bold: true, font: 'Arial', color: C.medBlue }, paragraph: { spacing: { before: 240, after: 80 }, outlineLevel: 2 } },
    ]
  },
  sections: [{
    properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1080, right: 1080, bottom: 1080, left: 1080 } } },
    headers: { default: new Header({ children: [new Paragraph({ alignment: AlignmentType.RIGHT, border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: C.erasmusBlue, space: 4 } }, spacing: { after: 80 }, children: [new TextRun({ text: 'Erasmus+ Management Portal — STU Bratislava  |  Strategic Analysis & Roadmap', size: 16, color: C.gray, font: 'Arial' })] })] }) },
    footers: { default: new Footer({ children: [new Paragraph({ alignment: AlignmentType.CENTER, border: { top: { style: BorderStyle.SINGLE, size: 4, color: C.erasmusBlue, space: 4 } }, spacing: { before: 80 }, children: [new TextRun({ text: 'Confidential — Internal Use Only  |  STU International Relations Office  |  Page ', size: 16, color: C.gray, font: 'Arial' }), new PageNumber({ font: 'Arial', size: 16, color: C.erasmusBlue })] })] }) },
    children: [
      // COVER
      new Paragraph({ spacing: { before: 1440, after: 480 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'ERASMUS+ MANAGEMENT PORTAL', bold: true, size: 72, color: C.erasmusBlue, font: 'Arial' })] }),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 160 }, children: [new TextRun({ text: 'ICM / KA171 Administration System', size: 40, color: C.gray, font: 'Arial', italics: true })] }),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 960 }, children: [new TextRun({ text: 'STU Bratislava — Slovak University of Technology', size: 32, color: C.medBlue, font: 'Arial', bold: true })] }),
      divider(C.erasmusBlue),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 480, after: 160 }, children: [new TextRun({ text: 'COMPLETE AUDIT, ANALYSIS, REDESIGN & STRATEGIC ROADMAP', bold: true, size: 28, color: C.darkBlue, font: 'Arial' })] }),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 480 }, children: [new TextRun({ text: 'Document Classification: Internal Strategic Planning  |  Version 1.0  |  June 2025', size: 18, color: C.gray, font: 'Arial' })] }),
      ...sp(2),
      infoBox([
        ['Document Type', 'Product Analysis, Architecture Design & Strategic Roadmap'],
        ['Scope', 'Erasmus+ ICM / KA171 Mobility Management — Full Platform'],
        ['Primary Institution', 'Slovak University of Technology in Bratislava (STU)'],
        ['Target Expansion', 'SaaS Platform for European & Global Universities'],
        ['Prepared By', 'Senior Product Manager / Full-Stack Architect / UX Architect'],
        ['Project Reference', '2023-1-SK01-KA171-HED-000148295'],
        ['Current Implementation', 'Single-page HTML Portal + Google Sheets Backend'],
        ['Recommended Stack', 'Next.js 14 + PostgreSQL + Node.js + Vercel/AWS'],
      ]),
      pageBreak(),

      // 1. EXECUTIVE SUMMARY
      h1('1. Executive Summary'),
      p('The Erasmus+ Management Portal is a purpose-built digital administration platform designed to replace manual Google Sheets-based workflows used by the International Relations Office (IRO) of STU Bratislava for managing Erasmus+ International Credit Mobility (ICM / KA171) projects. The system digitises, automates, and centralises the full lifecycle of academic mobility administration across 14 partner universities in 11 countries.'),
      ...sp(1),
      h2('1.1 What the System Is'),
      p('The portal is a full-stack web application providing an administrative CRM interface for IRO staff to manage every aspect of Erasmus+ mobilities — from initial planning and grant allocation through document collection, travel coordination, financial disbursement, and final reporting. It also lays the architectural foundation for a future student-facing public portal.'),
      ...sp(1),
      h2('1.2 Core Problem Statement'),
      p('STU\'s IRO currently manages 100+ staff and student mobilities per project cycle across four academic years using a complex multi-sheet Google Sheets workbook. This approach creates critical operational risks:'),
      bl('No referential integrity — data can be deleted or corrupted without audit trails'),
      bl('Manual formula-based grant calculations prone to human error (REF! errors observed in the actual data)'),
      bl('No automated alerting for missing documents, expired visas, or approaching deadlines'),
      bl('No role-based access — all coordinators share the same spreadsheet'),
      bl('No version history at the record level — only Google\'s generic revision history'),
      bl('Budget tracking scattered across multiple tabs with manual reconciliation'),
      bl('Impossible to scale to multi-faculty, multi-project, or multi-university contexts'),
      ...sp(1),
      h2('1.3 Business Value'),
      threeCol([
        ['Time Savings', '60–70%', 'Reduction in administrative hours through automation of document tracking, grant calculations, and reporting'],
        ['Error Reduction', '~95%', 'Elimination of spreadsheet formula errors, duplicate entries, and missing data through database constraints'],
        ['Compliance', '100%', 'Automated Erasmus+ compliance checks against EC guidelines ensure reporting accuracy'],
        ['Scalability', '10x', 'Platform can handle 10x more mobilities with no increase in administrative overhead'],
        ['SaaS Revenue Potential', '€50-200k+/yr', 'Annual recurring revenue potential per university client in commercial expansion phase'],
      ], ['Value Dimension', 'Impact', 'Description'], [2000, 1200, 6160]),
      ...sp(1),
      h2('1.4 Target Users'),
      p('Primary users are the IRO coordinators (currently Mgr. Lucia Miadoková and Mgr. Tereza Hubáčková, based on the PDF data), system administrators, financial officers, and faculty coordinators at STU. Secondary users in the expansion roadmap include partner institution managers and students accessing a public-facing portal.'),
      pageBreak(),

      // 2. PROJECT OVERVIEW
      h1('2. Project Overview'),
      h2('2.1 Main Purpose'),
      p('The portal digitises the complete lifecycle of Erasmus+ International Credit Mobility (ICM) under the KA171 action — covering outgoing and incoming mobilities for both students (short-term and long-term studies) and staff (teaching and training assignments) with partner universities in Western Balkans, Eastern Europe, Asia, Middle East, and Sub-Saharan Africa.'),
      ...sp(1),
      h2('2.2 Core Functional Areas'),
      twoCol([
        ['Mobility Planning', 'Plan and track mobility allocations per university, type, and academic year against Grant Agreement targets'],
        ['Participant Management', 'Full CRM for students and staff with personal data, academic context, and contact information'],
        ['Document Tracking', 'Per-participant checklist of 22+ required documents with real-time completion status and date stamps'],
        ['Financial Management', 'Individual Support, Travel Grant, Inclusion Support, OS calculations and multi-level budget oversight'],
        ['Partner University Management', 'IIA status tracking, IRO contacts, partner manager directory, project status monitoring'],
        ['Reporting & Compliance', 'Erasmus+ compliant reports, budget utilisation reports, country-level analytics'],
        ['Calendar & Scheduling', 'Mobility timeline view with departure/arrival tracking and document deadlines'],
        ['Notifications & Alerts', 'Automated alerts for missing documents, upcoming deadlines, and budget warnings'],
      ], ['Module', 'Description']),
      ...sp(1),
      h2('2.3 Typical User Journey — IRO Coordinator'),
      nb('Academic year begins: IRO coordinator opens portal, selects the active year (e.g., 2025/2026)'),
      nb('Partner universities and IIA agreements are verified and updated in the Universities module'),
      nb('Mobility slots are allocated per university and type (teaching, training, studies, PhD short)'),
      nb('Participants are nominated by partner institutions; coordinator creates Person + Mobility records'),
      nb('Document checklist is activated; system sends automated reminders for missing items'),
      nb('Grants are calculated automatically based on duration, country, seniority, and inclusion support'),
      nb('Accommodation and travel arrangements tracked per participant'),
      nb('During mobility: coordinator monitors active participants, updates document status'),
      nb('Post-mobility: final reports collected, BM entered, financial reconciliation performed'),
      nb('Annual report generated automatically from all collected data for EC submission'),
      pageBreak(),

      // 3. ANALYSIS
      h1('3. Analysis of the Existing Generated Portal'),
      h2('3.1 Strengths — What Is Implemented Well'),
      bl('Complete sidebar navigation with 11 pages covering all major functional areas', { bold: true }),
      bl('Sticky header with academic year selector — correctly scoped data by year'),
      bl('Responsive dark/light/STU Blue/purple theme system with CSS variables throughout'),
      bl('Slide-out profile panel with 7 tabs (General, Mobility, Academic, Finance, Contact, Documents, Notes)'),
      bl('Document checklist with real-time toggle and visual progress bar per participant'),
      bl('Chart.js integration with 5 live charts: country, budget, students vs staff, types, monthly activity'),
      bl('Global keyboard search (Ctrl+K) across all entities with result grouping'),
      bl('Kanban task board with To Do / In Progress / Completed columns'),
      bl('Contact participant modal with automatic email template generation based on missing documents'),
      bl('University profile cards with IIA/AIS status indicators'),
      bl('Budget page with expandable country rows showing breakdown by mobility type'),
      bl('Full calendar with monthly view and colour-coded events (departures, arrivals, deadlines)'),
      bl('Collapsible sidebar with tooltips in collapsed state'),
      bl('LocalStorage persistence for theme, language, year, and sidebar state'),
      bl('Slovak / English bilingual label support'),
      bl('Activity log widget and upcoming mobilities dashboard widget'),
      ...sp(1),
      h2('3.2 Weaknesses — What Is Missing'),
      bl('No real backend — all data is generated client-side and lost on page refresh', { bold: true }),
      bl('No authentication or access control — anyone with the URL can access all data'),
      bl('No actual Excel/CSV import — import button exists but has no file parsing logic'),
      bl('Student portal is absent — no public-facing website for students to explore opportunities'),
      bl('Grant calculation logic is static — not dynamically tied to Erasmus+ rate tables'),
      bl('No actual Google Drive API integration — buttons open placeholder URLs'),
      bl('No database — data is generated with Math.random() on every load, breaking consistency'),
      bl('Missing ISCED code validator and field-level input validation throughout all forms'),
      bl('No PDF/Excel report generation — only toast notification placeholders'),
      bl('No Organisational Support (OS) budget tracking — present in PDF but absent from portal'),
      bl('Cancelled mobilities archive missing (present in PDF as "ZRUŠENÉ MOBILITY")'),
      bl('No inclusion support tracking at the budget level'),
      bl('Missing CRZ document type (Slovak public contracts register — legally required)'),
      bl('No green travel incentive tracking (present in PDF data)'),
      bl('Missing contracted vs. actual mobility count comparison (critical for GA compliance)'),
      ...sp(1),
      h2('3.3 Risks'),
      bl('GDPR Risk: Storing full passport numbers, addresses, and PII client-side is a serious GDPR violation', { bold: true }),
      bl('Data Loss Risk: All generated sample data is lost on browser refresh — zero persistence for real data entry'),
      bl('Security Risk: No authentication means any URL visitor can view what appears to be real mobility data'),
      bl('Scalability Risk: Pure-frontend JavaScript cannot handle thousands of mobilities without severe performance issues'),
      bl('Maintenance Risk: All CSS, HTML, and JavaScript in a single 2000+ line file creates maintainability bottlenecks'),
      bl('Compliance Risk: Without server-side audit logging, the system cannot prove data changes for EC audits'),
      ...sp(1),
      h2('3.4 Overall Assessment Scores'),
      scoreTable([
        ['UX / Interface Design', '8.2 / 10', 'Excellent visual design, professional typography, smooth animations. Minor gaps in mobile optimisation.', C.lightGreen],
        ['Feature Coverage (UI)', '6.5 / 10', 'Core pages implemented but critical features (import, export, email, Drive) are placeholders.', C.lightOrange],
        ['Business Value (current)', '4.5 / 10', 'Without a real backend, the portal has zero production value. The architecture is a demo, not deployable.', C.lightRed],
        ['Scalability', '3.0 / 10', 'Single-file frontend with client-side state cannot scale. Needs complete backend architecture.', C.lightRed],
        ['Production Readiness', '2.5 / 10', 'No authentication, no database, no API, no GDPR compliance. Est. 6-9 months of engineering needed.', C.lightRed],
        ['Code Quality', '7.0 / 10', 'Well-structured JavaScript, consistent naming. However, monolithic single-file structure limits extensibility.', C.lightBlue],
        ['Design System Quality', '8.5 / 10', 'Excellent CSS variable system, consistent component library, good dark mode implementation.', C.lightGreen],
      ]),
      pageBreak(),

      // 4. PDF ANALYSIS
      h1('4. Analysis of the Google Sheets System (PDF)'),
      h2('4.1 Spreadsheet Architecture Overview'),
      p('The PDF reveals a multi-sheet Google Spreadsheet used as the operational backbone of STU\'s ICM project management. The workbook contains 9 distinct sheets, each serving a specialised administrative function. The data spans academic years 2023/2024, 2024/2025, and 2025/2026 across 14 partner universities in 11 countries.'),
      ...sp(1),
      threeCol([
        ['Tabuľka ICM 2023 Plán', 'Planning Sheet', 'Master mobility allocation plan: universities, types (teaching/training/studies/PhD), outgoing/incoming counts, duration, grant amounts per partner vs contracted totals'],
        ['Budget Overview', 'Financial Summary', 'Country-level budget tracking: total GA budget, inclusion budget, number of mobilities, OS allowance, used amounts, usage percentages, transfer notes'],
        ['Prehľad zmluvy', 'Contract Overview', 'Regional groupings (Western Balkans, Neighbourhood East, Asia, Middle East, Sub-Saharan Africa), per-partner planned allocations, coordinator assignments'],
        ['výučba_tréning', 'Staff Mobilities', '103 rows of staff teaching/training records: full personal data, mobility details, grant breakdown, seniority, teaching hours, ISCED codes'],
        ['štúdium', 'Student Mobilities', '67 rows of student study records: long-term/short-term classification, degree level, study field, grant calculations including inclusion support'],
        ['Doc_staff', 'Staff Documents', 'Per-staff document checklist: 22 document columns tracked as "ok", date stamps (e.g., "23.10. vyziadane"), or descriptive notes'],
        ['doc_student', 'Student Documents', 'Per-student document checklist: 24 document columns including Application, Nomination, LA, CV, ToR, Invitation, AIS, Insurance, Visa, BM, Confirmation, Survey, Green Travel'],
        ['projektoví manažéri', 'Partner Managers', 'Contact directory: country, university, STU coordinator, STU project manager, partner IRO contact, IIA status, AIS status, CRZ status'],
        ['ZRUŠENĚ MOBILITY', 'Cancelled Records', 'Archive of 5 cancelled mobilities with full data and cancellation dates — critical for GA reporting and audit trail'],
      ], ['Sheet Name', 'Type', 'Content Description'], [2600, 1600, 5160]),
      ...sp(1),
      h2('4.2 Grant Rate Structure Identified in PDF'),
      p('The PDF reveals the Erasmus+ ICM grant rate tables used by STU for the 2023 project cycle, which must be precisely replicated in the portal\'s financial calculation engine:'),
      threeCol([
        ['OUT Staff (do 14 dni)', 'EUR 180/day', 'Western Balkans region outgoing STU staff — up to 14 days duration'],
        ['OUT Staff (od 15 dni)', 'EUR 126/day', 'Reduced rate for outgoing STU staff — 15 days and above'],
        ['IN Staff (do 14 dni)', 'EUR 140/day', 'Incoming partner staff rate — up to 14 days'],
        ['IN Staff (od 15 dni)', 'EUR 98/day', 'Incoming partner staff reduced rate — 15+ days'],
        ['OUT Student (monthly)', 'EUR 700/month', 'Outgoing student monthly individual support rate'],
        ['IN Student (monthly)', 'EUR 800/month', 'Incoming student monthly individual support rate'],
        ['PhD Short (do 14 dni)', 'EUR 79/day', 'Short-term PhD mobility daily rate'],
        ['Inclusion Monthly', 'EUR 250/month', 'Monthly inclusion support supplement for participants with fewer opportunities'],
        ['Travel 5-14 days', 'EUR 100 lump sum', 'Short-term travel inclusion support'],
        ['Travel 15-30 days', 'EUR 150 lump sum', 'Medium-term travel inclusion support'],
        ['Distance band rates', 'EUR 23 to 1500', 'EC travel grant bands: 10-99km EUR23, 100-499km EUR180 to EUR1500 for 8000+km'],
      ], ['Rate Type', 'Amount', 'Description'], [2800, 1400, 5160]),
      ...sp(1),
      h2('4.3 Key Inefficiencies Identified for Automation'),
      twoCol([
        ['Manual date-based reminders in cells (e.g., "23.10. vyziadane")', 'Automated notification system with configurable reminder schedules and email dispatch'],
        ['REF! errors in grant formulas (observed in Plán sheet)', 'Server-side calculated fields with validation and error prevention at data layer'],
        ['Free-text document status ("vyziadane", "podpisuje")', 'Structured status enum: Not Started / Requested / Received / Rejected / Expired'],
        ['Year-end "ZABRATY RIADOK?" deletion notes', 'Proper cancellation workflow with audit trail, reason recording, and GA impact analysis'],
        ['Duplicate person entries across academic years', 'Single Person record with multiple Mobility relationships — one record per individual'],
        ['Manual OS/inclusion calculations', 'Automatic rate-table-based calculation engine triggered on date/country entry'],
        ['Budget transfer footnotes in cells', 'Formal transfer request workflow with approval, documentation, and audit trail'],
        ['Scattered free-text notes column', 'Structured notes with author attribution, timestamp, and searchable categories'],
        ['Manual CRZ/AIS status tracking', 'Integration-ready status fields with external system sync notifications'],
        ['Accommodation tracked as text notes', 'Structured accommodation records: provider, facility, dates, amounts, confirmation'],
      ], ['Current Spreadsheet Inefficiency', 'Portal Automation Solution']),
      pageBreak(),

      // 5. MIGRATION
      h1('5. Migration from Google Sheets to Web Platform'),
      h2('5.1 Staff Sheet (výučba_tréning) Column Mapping'),
      twoCol([
        ['Č. zmluvy (Contract No.)', 'mobilities.contract_number VARCHAR UNIQUE NOT NULL'],
        ['Fakulta STU', 'faculties.code FK (FCHPT/FIIT/UM/SvF/MTF/REC)'],
        ['Koordinátorka', 'users.id FK (role=coordinator)'],
        ['Flow (IN/OUT)', 'mobilities.flow ENUM(incoming, outgoing)'],
        ['Type (teaching/training)', 'mobilities.type ENUM(teaching, training, studies, phd_short)'],
        ['Meno / Priezvisko', 'persons.first_name, persons.last_name'],
        ['Dátum narodenia', 'persons.date_of_birth DATE'],
        ['Krajina / Univerzita / Fakulta', 'countries.id + partner_universities.id + departments.name FKs'],
        ['Začiatok / Koniec', 'mobilities.start_date DATE, mobilities.end_date DATE'],
        ['Mesiace/Dni-C', 'COMPUTED: DATE_DIFF(end_date, start_date) automatically'],
        ['Grant-I (Individual Support)', 'grants.individual_support DECIMAL(10,2)'],
        ['Grant Cestovné (Travel)', 'grants.travel_grant DECIMAL(10,2) from travel_rate_tables'],
        ['Platba leteniek (Flight payment)', 'payments.amount WHERE type=flight_payment'],
        ['Celkový grant mínus letenky', 'COMPUTED: grants.total_grant - SUM(payments.amount WHERE type=flight)'],
        ['Štátna príslušnosť / Nationality', 'persons.nationality_sk, persons.nationality_en VARCHAR'],
        ['Pohlavie (Gender)', 'persons.gender ENUM(M, F, Other)'],
        ['Adresa / Číslo pasu', 'persons.address ENCRYPTED, persons.passport_number ENCRYPTED'],
        ['Telefón / Email', 'persons.phone ENCRYPTED, persons.email VARCHAR'],
        ['Seniority', 'staff_mobility_details.seniority ENUM(junior, intermediate, senior, professor, full_professor)'],
        ['Ak. Rok (Academic Year)', 'mobilities.academic_year VARCHAR (e.g., "2024/2025")'],
        ['ISCED kód', 'mobilities.isced_code VARCHAR + FK to isced_codes reference table'],
        ['Teaching hours', 'staff_mobility_details.teaching_hours INTEGER (min 8h/week per EC rules)'],
      ], ['Spreadsheet Column', 'Database Implementation']),
      ...sp(1),
      h2('5.2 Document Tracking Column Mapping'),
      p('Both Doc_staff and doc_student sheets use a hybrid status system (text notes + "ok"). The portal replaces this with a structured documents table:'),
      twoCol([
        ['Application', 'documents: type=application, status ENUM, received_date'],
        ['Nomination', 'documents: type=nomination, sent_date, received_date'],
        ['Learning Agreement (LA)', 'documents: type=learning_agreement + la_versions table for amendments'],
        ['Invitation', 'documents: type=invitation, issuing_institution'],
        ['Insurance', 'documents: type=insurance, expiry_date (for automated expiry alerts)'],
        ['Visa', 'documents: type=visa, expiry_date, issuing_country'],
        ['Boarding Pass / Letenka', 'documents: type=boarding_pass, transport_type (plane/train/bus/car)'],
        ['BM (Confirmation of Mobility)', 'documents: type=confirmation_of_mobility, signed_by_host'],
        ['GA (Grant Agreement)', 'documents: type=grant_agreement, signature_date'],
        ['CRZ', 'documents: type=crz_registration (Slovak public contracts register — legally required)'],
        ['Výpis z účtu (Bank statement)', 'documents: type=bank_statement, amount_confirmed'],
        ['Survey', 'documents: type=eu_survey, completion_url, completion_date'],
        ['BM REIMBURSEMENT', 'payments: type=reimbursement, amount, receipt_date'],
        ['GREEN TRAVEL', 'mobilities.green_travel BOOLEAN + mobilities.transport_type ENUM'],
        ['Cash Payment Request', 'payments.method ENUM(bank_transfer, cash) + cash_request_document FK'],
        ['"ok" value', 'documents.status = received, documents.received_date = CURRENT_DATE'],
        ['Date note ("23.10. vyziadane")', 'documents.requested_date DATE + documents.notes TEXT'],
        ['Descriptive note ("zabookovat po vizach")', 'documents.notes TEXT with author_id FK and created_at TIMESTAMP'],
      ], ['Document Column / Status Value', 'Database Implementation']),
      ...sp(1),
      h2('5.3 Budget Sheet Mapping'),
      twoCol([
        ['Country', 'countries table with budget_allocations JOIN'],
        ['Mobility budget GA', 'budget_allocations.total_amount per country per grant_agreement'],
        ['Inclusion GA', 'budget_allocations.inclusion_amount per country'],
        ['No Mobility GA', 'COUNT(mobilities) WHERE country_id = x GROUP BY status'],
        ['OS GA (Organisational Support)', 'budget_allocations.os_amount = EUR500 x mobility_count'],
        ['TOTAL Used', 'SUM(payments.amount) WHERE paid = true, grouped by country'],
        ['% Used', 'COMPUTED field: used_amount / total_amount * 100, refreshed on payment entry'],
        ['Budget transfer footnotes', 'budget_transfers table: from/to country, amount, approved_by, approved_at'],
        ['Afrika spolu % (Africa total)', 'Aggregate view: SUM across Africa-region countries'],
        ['Tanzánia exceeded 120.65%', 'Automated alert: when used_pct > 100%, generate Critical notification'],
      ], ['Spreadsheet Cell / Column', 'Database Implementation']),
      pageBreak(),

      // 6. AUTHENTICATION
      h1('6. User Authentication System'),
      h2('6.1 Authentication Methods'),
      h3('Primary Authentication'),
      bl('Email + Password: bcrypt password hashing (cost factor 12+). Minimum 12 characters with uppercase, lowercase, number, and symbol requirements.'),
      bl('University SSO (SAML 2.0 / OAuth 2.0): Integration with STU\'s Azure AD / Shibboleth identity provider for Single Sign-On.'),
      bl('Magic Link: Passwordless email authentication — coordinator receives a time-limited (15 minutes) login link.'),
      ...sp(1),
      h3('Multi-Factor Authentication (MFA)'),
      bl('TOTP (Time-based One-Time Password): Google Authenticator / Authy compatible. Mandatory for Admin and Financial Officer roles.'),
      bl('Email OTP: 6-digit code sent to registered email. Fallback option for all roles.'),
      bl('Trusted device: 30-day device trust with cryptographically secure HTTP-only cookie.'),
      ...sp(1),
      h2('6.2 Session & Token Management'),
      bl('JWT access tokens (15-minute expiry) + HTTP-only refresh tokens (7-day expiry with rotation)'),
      bl('Concurrent session limit: maximum 3 active sessions per user account'),
      bl('Forced logout from all sessions on password change or security event'),
      bl('All authentication events logged: login, logout, failed attempts, MFA events, IP address'),
      ...sp(1),
      h2('6.3 Password Policy'),
      bl('Minimum 12 characters: uppercase, lowercase, number, and symbol required'),
      bl('Password history: last 5 passwords cannot be reused'),
      bl('Account lockout after 5 failed attempts (progressive: 5min → 30min → 2hr)'),
      bl('Password reset: time-limited email link (1-hour expiry)'),
      pageBreak(),

      // 7. ROLES
      h1('7. User Roles & Permissions (RBAC)'),
      p('The system implements Role-Based Access Control (RBAC) with five distinct roles, each scoped to appropriate data domains. Permissions are enforced at both the API middleware layer and the UI feature flag layer.'),
      ...sp(1),
      threeCol([
        ['System Administrator', 'Full system access', 'User management, system settings, all data, audit logs, backup/restore, rate table management'],
        ['Erasmus Coordinator (IRO)', 'Full mobility management', 'All students, staff, documents, budgets, reports, partner universities — scoped to assigned projects'],
        ['Faculty Coordinator', 'Faculty-scoped read + approval', 'View mobilities for own faculty, approve LA and documents, read-only budget for own faculty, recognition tracking'],
        ['Financial Officer', 'Financial data only', 'Budget management, grant calculations, payment tracking, financial reports — no personal data editing'],
        ['Student (Public Portal)', 'Public portal only', 'No access to CRM — dedicated public portal with anonymised statistics and own mobility status'],
      ], ['Role', 'Access Level', 'Capabilities'], [2400, 2000, 4960]),
      ...sp(1),
      h2('7.1 Detailed Permission Matrix'),
      new Table({
        width: { size: 9360, type: WidthType.DXA },
        columnWidths: [2600, 1340, 1200, 1380, 1200, 1640],
        rows: [
          new TableRow({ tableHeader: true, children: [
            cell('Resource', { fill: C.erasmusBlue, bold: true, color: C.white, size: 16, width: 2600 }),
            cell('Admin', { fill: C.erasmusBlue, bold: true, color: C.white, size: 16, width: 1340, align: AlignmentType.CENTER }),
            cell('Coordinator', { fill: C.erasmusBlue, bold: true, color: C.white, size: 16, width: 1200, align: AlignmentType.CENTER }),
            cell('Faculty', { fill: C.erasmusBlue, bold: true, color: C.white, size: 16, width: 1380, align: AlignmentType.CENTER }),
            cell('Financial', { fill: C.erasmusBlue, bold: true, color: C.white, size: 16, width: 1200, align: AlignmentType.CENTER }),
            cell('Student', { fill: C.erasmusBlue, bold: true, color: C.white, size: 16, width: 1640, align: AlignmentType.CENTER }),
          ]}),
          ...([
            ['Student/Staff PII', 'Full CRUD', 'Full CRUD', 'Read Only', 'No Access', 'Own Record'],
            ['Financial & Grants', 'Full CRUD', 'Read + Edit', 'Read (faculty)', 'Full CRUD', 'No Access'],
            ['Documents', 'Full CRUD', 'Full CRUD', 'Read + Approve', 'Read Only', 'Own Docs'],
            ['Partner Universities', 'Full CRUD', 'Full CRUD', 'Read Only', 'Read Only', 'Public Only'],
            ['User Management', 'Full CRUD', 'No Access', 'No Access', 'No Access', 'No Access'],
            ['Audit Logs', 'Full Access', 'Own Actions', 'No Access', 'Finance Only', 'No Access'],
            ['Budget Transfers', 'Approve', 'Request', 'No Access', 'Approve', 'No Access'],
            ['Reports & Export', 'All Reports', 'Project Reports', 'Faculty Reports', 'Financial', 'No Access'],
          ]).map((r, i) => new TableRow({ children: r.map((t, j) => cell(t, {
            fill: i%2===0?C.white:C.lightGray, size: 16, bold: j===0,
            color: j===0?C.darkBlue:(t==='No Access'?C.red:(t.includes('Full')||t.includes('All')?C.green:C.gray)),
            width: [2600,1340,1200,1380,1200,1640][j]
          })) }))
        ]
      }),
      pageBreak(),

      // 8. STUDENT PORTAL
      h1('8. Student Public Portal'),
      p('The student public portal is a completely separate Next.js application from the administrative CRM — distinct subdomain (erasmus.stuba.sk), separate codebase, no access to internal CRM data. It exposes only anonymised and aggregated statistics.'),
      ...sp(1),
      h2('8.1 Interactive World Map'),
      bl('Leaflet.js or Mapbox-powered vector world map with all 14 partner countries highlighted'),
      bl('Clickable country → university list → university detail page with mobility statistics'),
      bl('Filter by mobility type, year, and faculty to update map highlighting in real-time'),
      bl('Cluster markers for multi-university countries (e.g., Ukraine: 3 universities)'),
      bl('Mobile-responsive touch/pinch zoom with accessibility keyboard navigation'),
      ...sp(1),
      h2('8.2 Public Statistics Dashboard'),
      bl('Animated KPI counters: total mobilities, active universities, active countries, staff/student split'),
      bl('Top 10 destination countries — interactive bar chart with year filter'),
      bl('Monthly trend chart showing peak departure/arrival periods'),
      bl('Faculty participation breakdown (FCHPT, FIIT, UM, SvF, MTF, REC)'),
      bl('All data is fully anonymised — no names, passport numbers, or contact details exposed publicly'),
      ...sp(1),
      h2('8.3 Partner University Directory'),
      bl('Dedicated public profile page per university with: name, country, city, website link'),
      bl('Available study fields and ISCED codes for student information'),
      bl('Anonymised mobility statistics: exchange count per year (no personal data)'),
      bl('IIA active/expired status indicator — shows whether exchanges are currently available'),
      bl('STU contact coordinator name and IRO email for student enquiries'),
      bl('Accommodation information and campus photos (if provided by partner)'),
      ...sp(1),
      h2('8.4 Student Personal Portal (Post-Nomination)'),
      p('Students who have been nominated receive login credentials to a personal sub-section:'),
      bl('View own mobility status, upcoming deadlines, and document checklist'),
      bl('Upload required documents (passport scan, insurance certificate, signed LA)'),
      bl('Track document review status in real-time with coordinator comments'),
      bl('Receive targeted notifications for missing items and approaching deadlines'),
      bl('Complete online post-mobility participant survey'),
      pageBreak(),

      // 9. DATABASE
      h1('9. Database Design'),
      h2('9.1 Technology Recommendation'),
      infoBox([
        ['Database Engine', 'PostgreSQL 16 — ACID compliant, JSON support, row-level security, excellent for complex relational queries'],
        ['ORM', 'Prisma ORM (Node.js/TypeScript) — type-safe queries, auto-migrations, excellent developer experience'],
        ['Connection Pooling', 'PgBouncer — required for handling concurrent users in university/SaaS context'],
        ['Encryption', 'pgcrypto extension for sensitive field encryption (passport, phone, address, IBAN)'],
        ['Backup', 'Automated daily snapshots to S3-compatible storage with 30-day retention and PITR'],
        ['Hosting', 'Supabase (managed PostgreSQL) or AWS RDS for production; Docker Compose for development'],
        ['Multi-tenancy (SaaS)', 'Schema-per-tenant: each university gets isolated schema, shared public reference data'],
      ]),
      ...sp(1),
      h2('9.2 Core Table Structures'),
      h3('Users & Authentication'),
      twoCol([
        ['users', 'id UUID PK, email VARCHAR UNIQUE, password_hash VARCHAR, role_id FK, faculty_id FK, first_name, last_name, phone_encrypted, language ENUM(en,sk), theme ENUM, mfa_enabled BOOLEAN, mfa_secret_encrypted, last_login, is_active, created_at, updated_at'],
        ['roles', 'id, name ENUM(admin/coordinator/faculty_coord/financial/student), permissions JSONB'],
        ['sessions', 'id, user_id FK, refresh_token_hash VARCHAR, ip_address INET, user_agent TEXT, expires_at, revoked_at'],
        ['audit_log', 'id, user_id FK, action VARCHAR, resource_type VARCHAR, resource_id UUID, old_value JSONB, new_value JSONB, ip_address INET, timestamp TIMESTAMPTZ'],
      ], ['Table', 'Key Fields']),
      ...sp(1),
      h3('Institutional & Geographic'),
      twoCol([
        ['countries', 'id, iso_code CHAR(2) UNIQUE, name_sk, name_en, flag_emoji, erasmus_region VARCHAR, travel_distance_band VARCHAR, is_active'],
        ['partner_universities', 'id UUID, country_id FK, name VARCHAR, name_short, city, website, iia_status ENUM(active/expired/pending), iia_signed_date DATE, ais_status, is_active, notes TEXT'],
        ['faculties', 'id, code ENUM(FCHPT/FIIT/UM/SvF/MTF/REC), name_sk, name_en, dean_email, ero_email'],
        ['partner_contacts', 'id UUID, university_id FK, name, email, phone, role ENUM(iro/project_manager/coordinator), is_primary BOOLEAN, notes'],
      ], ['Table', 'Key Fields']),
      ...sp(1),
      h3('Person & Mobility'),
      twoCol([
        ['persons', 'id UUID, first_name, last_name, date_of_birth DATE, gender ENUM, nationality_sk, nationality_en, address_encrypted TEXT, place_of_birth, passport_number_encrypted VARCHAR, phone_encrypted VARCHAR, email VARCHAR, is_stu_staff BOOLEAN, created_at'],
        ['mobilities', 'id UUID, contract_number VARCHAR UNIQUE, person_id FK, type ENUM(teaching/training/studies/phd_short), flow ENUM(incoming/outgoing), status ENUM(upcoming/active/completed/cancelled), faculty_id FK, coordinator_id FK, university_id FK, department_name, start_date DATE, end_date DATE, duration_months COMPUTED, academic_year VARCHAR, isced_code, green_travel BOOLEAN, transport_type ENUM, cancelled_at, cancel_reason, created_at, updated_at'],
        ['staff_mobility_details', 'id, mobility_id FK UNIQUE, seniority ENUM(junior/intermediate/senior/professor/full_professor), teaching_hours INTEGER, course_names TEXT'],
        ['student_mobility_details', 'id, mobility_id FK UNIQUE, degree_level SMALLINT(1/2/3), duration_type ENUM(short/long), study_field_sk, study_field_en, recognition_status ENUM'],
        ['mobility_history', 'id, mobility_id FK, changed_by FK users, field_name VARCHAR, old_value TEXT, new_value TEXT, changed_at TIMESTAMPTZ'],
      ], ['Table', 'Key Fields']),
      ...sp(1),
      h3('Financial'),
      twoCol([
        ['grant_agreements', 'id UUID, project_number VARCHAR UNIQUE, title, start_year, end_year, total_budget DECIMAL, inclusion_budget DECIMAL, os_budget DECIMAL, signed_date DATE, ec_reference VARCHAR'],
        ['budget_allocations', 'id, ga_id FK, university_id FK, mobility_type, flow, year VARCHAR, planned_count INTEGER, planned_budget DECIMAL, is_agreed BOOLEAN, notes'],
        ['grants', 'id UUID, mobility_id FK UNIQUE, individual_support_rate DECIMAL, individual_support_total DECIMAL, travel_distance_km INTEGER, travel_grant DECIMAL, inclusion_support DECIMAL, os_amount DECIMAL, total_grant DECIMAL, final_grant DECIMAL, calculated_at TIMESTAMPTZ'],
        ['payments', 'id UUID, mobility_id FK, type ENUM(accommodation/flight/grant/reimbursement/os/cash), amount DECIMAL, payment_date DATE, bank_name, iban_encrypted TEXT, swift VARCHAR, method ENUM(bank/cash), invoice_number, notes, paid_by FK users'],
        ['budget_transfers', 'id UUID, ga_id FK, from_country_id FK, to_country_id FK, amount DECIMAL, reason TEXT, approved_by FK users, approved_at TIMESTAMPTZ, created_at'],
        ['travel_rate_tables', 'id, year_from SMALLINT, year_to SMALLINT, distance_band_min INTEGER, distance_band_max INTEGER, grant_amount DECIMAL'],
        ['daily_rate_tables', 'id, year_from, year_to, mobility_type, flow, seniority_group ENUM, duration_band ENUM(do14/od15), daily_rate DECIMAL'],
      ], ['Table', 'Key Fields']),
      ...sp(1),
      h3('Documents'),
      twoCol([
        ['documents', 'id UUID, mobility_id FK, type ENUM(application/nomination/la/invitation/insurance/visa/boarding_pass/confirmation/ga/crz/survey/bm_reimbursement/green_travel/cash_request/transcript/final_report/tor/cv/proof_of_payment), status ENUM(not_started/requested/received/rejected/expired), requested_date DATE, received_date DATE, expiry_date DATE, file_path VARCHAR (S3 key), file_size BIGINT, uploaded_by FK, notes TEXT, created_at'],
        ['la_versions', 'id, document_id FK, version_number SMALLINT, changes_description TEXT, signed_by_student BOOLEAN, signed_by_stu BOOLEAN, signed_by_host BOOLEAN, signed_at DATE, file_path VARCHAR'],
        ['accommodation', 'id UUID, mobility_id FK, provider ENUM(stu/university/private), facility_name VARCHAR, room_number, check_in DATE, check_out DATE, amount_eur DECIMAL, confirmation_document FK documents, notes'],
      ], ['Table', 'Key Fields']),
      pageBreak(),

      // 10. MODULES
      h1('10. System Modules'),
      threeCol([
        ['01 Dashboard Module', 'Overview & KPIs', 'Role-specific dashboards with live KPI cards, Chart.js visualisations, alert centre, recent activity feed, upcoming mobility timeline. Separate widget layouts per role.'],
        ['02 Mobility Management', 'Central Registry', 'Master list of all mobilities with advanced filtering, bulk operations, status management, Gantt timeline view, and links to all sub-records.'],
        ['03 Student Management', 'Student CRM', 'Full student profile management: personal data, academic context, mobility details, document checklist, financial summary, notes, Google Drive integration.'],
        ['04 Staff Management', 'Staff CRM', 'Identical structure to Student module with additional fields: seniority, teaching hours, course names, ISCED code validation.'],
        ['05 Document Management', 'Document Tracking', 'Cross-participant document status matrix, automated reminder generation, document upload/download, version tracking for Learning Agreements, compliance score per participant.'],
        ['06 Financial Management', 'Budget & Grants', 'Grant calculation engine with dynamic rate tables, budget allocation vs. actual, payment recording, OS tracking, inclusion support management, budget transfer workflow.'],
        ['07 Partner University Module', 'Partnership CRM', 'University profiles, IIA/AIS status tracking, partner contact directory, mobility allocation per university, budget utilisation, annual review workflow.'],
        ['08 Partner Manager Module', 'External Contacts', 'Searchable directory of all external partner managers and IRO contacts with communication log, reminder system, and project status indicators.'],
        ['09 Calendar Module', 'Scheduling', 'Month/week/agenda views with arrivals, departures, document deadlines, budget deadlines, visa expiry events. iCal export for external calendar integration.'],
        ['10 Task Management', 'Team Workflow', 'Kanban board for coordinator tasks: create, assign, deadline, priority, link to mobility/university/student records. Team and personal views.'],
        ['11 Notification Centre', 'Alerts', 'Centralised inbox for all system alerts grouped by priority. Configurable notification rules. Email digest. Mark read/unread. Filter by type.'],
        ['12 Reporting Module', 'Analytics & Reports', 'Pre-built Erasmus+ compliance reports, country reports, faculty reports, financial reports, export in XLSX/CSV/PDF. Custom report builder.'],
        ['13 User Management', 'System Admin', 'Create/edit/deactivate users, assign roles and faculty scope, view session history, force password reset, activity audit log viewer.'],
        ['14 Settings Module', 'Configuration', 'Grant rate tables editor, academic year management, notification rules, email templates, Google Drive configuration, backup and restore.'],
        ['15 Student Public Portal', 'Public Website', 'Separate Next.js application: interactive world map, university directory, anonymised statistics, student pre-application enquiry form.'],
        ['16 Import/Export Engine', 'Data Migration', 'Excel/CSV import with validation preview, field mapping wizard matching existing spreadsheet columns exactly, duplicate detection, rollback on error.'],
      ], ['Module', 'Category', 'Description'], [2200, 1700, 5460]),
      pageBreak(),

      // 11. WORKFLOWS
      h1('11. Key Workflows'),
      h2('11.1 Outgoing Student Mobility (Step by Step)'),
      twoCol([
        ['1. Planning', 'Coordinator creates mobility slot against University + Academic Year in Planning module'],
        ['2. Nomination', 'Student nominated by faculty; coordinator creates Person record + Mobility record (status: Upcoming)'],
        ['3. Application Package', 'System auto-generates document checklist; Application received and marked'],
        ['4. Nomination to Partner', 'Coordinator sends nomination to partner university IRO; Nomination doc marked sent'],
        ['5. Learning Agreement', 'Student creates LA; uploaded; faculty coordinator reviews → approves; LA v1 stamped'],
        ['6. Invitation', 'Partner sends invitation; uploaded; status auto-updates; departure checklist activated'],
        ['7. Pre-Departure Checks', 'System alerts if Insurance / Visa / Boarding Pass missing 7 days before departure'],
        ['8. Grant Calculation', 'System auto-calculates from rate tables; coordinator reviews and approves amount'],
        ['9. Grant Agreement Signed', 'CRZ registration → GA uploaded and signed; initial grant payment initiated'],
        ['10. Active', 'Status auto-changes to Active on start_date; accommodation confirmation recorded'],
        ['11. LA Amendments', 'Any LA changes create new version in la_versions table with diff tracking'],
        ['12. Return', 'Status changes to Completed on end_date; post-mobility doc checklist activated'],
        ['13. Post-Mobility Documents', 'Confirmation of Mobility Period, Survey, Final Report tracked; auto-reminders sent'],
        ['14. Financial Closure', 'Final grant calculated; reimbursement processed; unused budget returned to allocation'],
        ['15. Recognition', 'Academic credits recognised; AIS system updated; mobility record closed'],
      ], ['Step', 'Action']),
      ...sp(1),
      h2('11.2 Budget Transfer Workflow'),
      nb('Coordinator identifies budget shortfall or need for reallocation between partner country allocations'),
      nb('Budget Transfer Request created: from_country, to_country, amount, justification text'),
      nb('System validates: transfer does not exceed 50% of source country OS allocation (EC rule)'),
      nb('Financial Officer reviews request — approves or rejects with comments'),
      nb('On approval: budget_allocations table updated; audit log entry created automatically'),
      nb('Notification sent to requesting coordinator with approval details'),
      nb('Transfer recorded in budget_transfers table with full details for EC audit trail'),
      pageBreak(),

      // 12. DASHBOARDS
      h1('12. Dashboard Designs by Role'),
      h2('12.1 Administrator Dashboard'),
      bl('System health panel: active users, last backup timestamp, error rate, recent audit activity'),
      bl('All project KPIs across all academic years with year-over-year comparison charts'),
      bl('Data completeness score: percentage of all mobility records fully completed across all coordinators'),
      bl('User activity log: last 50 changes with user attribution and resource links'),
      bl('GDPR compliance widget: data retention warnings for records older than 5 years'),
      ...sp(1),
      h2('12.2 Coordinator Dashboard'),
      bl('My projects: active mobility count per academic year with status breakdown (Active/Upcoming/Completed/Cancelled)'),
      bl('Alert centre: critical (missing docs before departure), warnings (upcoming deadlines), info (completions)'),
      bl('Document completion rate across all my assigned participants — lowest scorers highlighted'),
      bl('Budget utilisation: my projects vs. contracted amounts with traffic-light colour coding'),
      bl('Upcoming departures/arrivals (next 14 days) with one-click quick actions'),
      bl('Task board summary: my open tasks with due date countdown'),
      ...sp(1),
      h2('12.3 Financial Officer Dashboard'),
      bl('Total budget across all active Grant Agreements with overall utilisation percentage'),
      bl('Country budget matrix: all countries, allocated vs. used vs. remaining with visual bars'),
      bl('Payment queue: pending payments awaiting processing with participant details'),
      bl('OS tracking: organisational support per mobility count vs. total claimed'),
      bl('Pending budget transfer requests awaiting financial approval'),
      bl('Financial report shortcuts: one-click export for EC reporting periods'),
      ...sp(1),
      h2('12.4 Faculty Coordinator Dashboard'),
      bl('My faculty\'s active mobilities: student count, staff count, incoming vs. outgoing breakdown'),
      bl('Document approval queue: Learning Agreements and documents requiring my signature'),
      bl('My faculty budget allocation and utilisation (read-only view)'),
      bl('Student recognition status: pending academic credits to be formally awarded'),
      pageBreak(),

      // 13. REPORTS
      h1('13. Reports & Analytics'),
      threeCol([
        ['Erasmus+ Annual Activity Report', 'Compliance', 'Full EC-format report: all mobility statistics, grant utilisation, participant breakdown by country/type/gender/study field — ready for Mobility Tool+ submission'],
        ['Grant Agreement Utilisation Report', 'Financial', 'Per-university comparison of contracted vs. actual mobilities and budget with variance analysis and over/under utilisation flags'],
        ['Country Budget Report', 'Financial', 'Per-country: GA amount, used, remaining, OS, inclusion support, transfers, % utilisation with traffic-light indicators'],
        ['Document Completion Report', 'Operational', 'All participants with document completion % — sorted by risk (lowest completion first), filterable by coordinator and departure date'],
        ['Cancelled Mobilities Report', 'Compliance', 'All cancelled mobilities with reasons, GA budget impact, and whether cancellation was notified to EC within required timeframe'],
        ['Green Travel Report', 'Compliance', 'All mobilities flagged for green travel — counts, reimbursement amounts, transport modes for EC sustainability reporting'],
        ['Partner University Performance Report', 'Strategic', 'Mobility volume, budget utilisation, document submission timeliness, and IIA status per partner — annual review input'],
        ['Faculty Participation Report', 'Academic', 'Mobilities per faculty, coordinator, and department with year-over-year trends and under-utilisation identification'],
        ['Inclusion Support Report', 'Compliance', 'All participants receiving inclusion support with justification codes and amounts — EC audit-ready with supporting documentation links'],
        ['Financial Reconciliation Report', 'Financial', 'Per-participant: planned grant vs. final grant vs. actual payments processed with variance explanations'],
        ['Survey Completion Report', 'Compliance', 'EU Participant Survey completion rates vs. EC minimum thresholds (100% expected) with chase status per participant'],
        ['Custom Analytics Report', 'Intelligence', 'User-configurable: select dimensions, metrics, date range, group by, sort — export to XLSX/CSV/PDF'],
      ], ['Report Name', 'Category', 'Description'], [3000, 1400, 4960]),
      pageBreak(),

      // 14. NOTIFICATIONS
      h1('14. Notification System Design'),
      h2('14.1 Notification Channels'),
      bl('In-app: real-time badge and notification centre within the portal (WebSocket or polling)'),
      bl('Email digest: daily or weekly summary of pending actions (configurable per user in Settings)'),
      bl('Immediate email: critical alerts — departure tomorrow with missing docs, budget exceeded'),
      bl('Optional SMS: critical pre-departure alerts via Twilio for coordinators with high-volume projects'),
      ...sp(1),
      h2('14.2 Automated Notification Rules'),
      threeCol([
        ['Missing Insurance', 'Critical', 'Insurance not received AND departure < 7 days — alert coordinator + auto-email draft to participant'],
        ['Missing Visa', 'Critical', 'Visa required AND not received AND departure < 14 days'],
        ['Departure Tomorrow', 'Critical', 'start_date = tomorrow AND any required document missing'],
        ['Budget Exceeded', 'Critical', 'Country used% > 100% OR university used% > allocated amount'],
        ['Missing Learning Agreement', 'Warning', 'LA not received AND departure < 21 days'],
        ['Missing Post-Mobility Survey', 'Warning', 'Mobility completed > 7 days AND survey not received'],
        ['Missing Final Report', 'Warning', 'Mobility completed > 30 days AND final report not submitted'],
        ['IIA Agreement Expiring', 'Warning', 'iia_expiry_date < 60 days from today'],
        ['Upcoming Mobility', 'Info', 'start_date in 30 days — pre-departure checklist review reminder'],
        ['Budget Warning (85%)', 'Warning', 'Country used% > 85% — approaching limit, no transfer requests yet'],
        ['Visa Expiry During Mobility', 'Warning', 'visa expiry_date < 30 days for an ongoing (Active) mobility'],
        ['Overdue Task', 'Warning', 'Task due_date has passed and status != completed'],
        ['Green Travel Reimbursement Due', 'Info', 'Green travel flagged mobility completed > 7 days and EUR50 reimbursement not processed'],
      ], ['Trigger', 'Priority', 'Action / Description'], [2600, 1000, 5760]),
      pageBreak(),

      // 15. AI
      h1('15. AI-Powered Features'),
      h2('15.1 AI Coordinator Assistant'),
      p('A Claude API or GPT-4o-powered conversational assistant embedded in the portal sidebar, with access to live database context through secure server-side tool calls:'),
      bl('"How many teaching mobility slots remain for Tanzania in 2025/2026?" → instant database query result'),
      bl('"Generate reminder emails for all participants missing insurance departing in the next 10 days" → personalised drafts for each'),
      bl('"What is the travel grant for a 12-day training visit to Bhutan?" → rate table lookup with calculation shown'),
      bl('"Which partner universities still have open incoming student slots?" → live database query with visual summary'),
      bl('"Create a budget transfer request from Nigeria allocation to Tanzania" → form pre-populated for coordinator approval'),
      ...sp(1),
      h2('15.2 Intelligent Document Processing'),
      bl('Passport scan OCR: automatically extract name, passport number, nationality, and expiry from uploaded passport image'),
      bl('Insurance document parser: extract coverage period, policy number, and coverage type from uploaded PDF'),
      bl('Learning Agreement validator: check LA structure against required fields, flag missing sections before coordinator review'),
      bl('Duplicate person detection: flag if same name + date of birth combination already exists in another mobility record'),
      ...sp(1),
      h2('15.3 Predictive Analytics'),
      bl('Budget forecasting: based on current mobility pipeline and historical spend patterns, predict end-of-year utilisation per country'),
      bl('Document completion risk model: identify which participants are at statistical risk of missing their departure with documents incomplete'),
      bl('Partner performance prediction: based on historical submission times, predict which partners are likely to cause document delays'),
      bl('Mobility anomaly detection: flag unusual grant amounts, duplicate payments, or data inconsistencies requiring coordinator review'),
      ...sp(1),
      h2('15.4 Natural Language Search'),
      p('"Show me all incoming students from Ukraine arriving in spring 2025 with missing insurance" → parsed to parameterised database query with visual results. Eliminates the need for coordinators to navigate multiple filter dropdowns for complex queries.'),
      pageBreak(),

      // 16. INNOVATIVE FEATURES
      h1('16. Innovative Features (Priority Ranked)'),
      h2('16.1 High Priority'),
      threeCol([
        ['Live Grant Calculator Widget', 'Interactive modal: enter country, dates, type, inclusion → instant grant breakdown with rate table sources cited. Eliminates coordinator calculation errors.', 'Medium complexity / very high daily value'],
        ['Smart Document Email Generator', 'One-click: select participant → system identifies missing docs → personalised multi-language email with specific deadline dates and upload instructions.', 'Low complexity / immediate time savings'],
        ['Mobility Timeline Gantt View', 'Visual Gantt chart of all mobilities on a timeline — identify scheduling conflicts, peak periods, and university slot utilisation at a glance.', 'Medium complexity / high strategic value'],
        ['IIA Renewal Tracker with Auto-Reminders', 'Automated 90/60/30-day IIA expiry workflow. System generates renewal request email template to partner university IRO.', 'Low complexity / prevents critical compliance failures'],
        ['Google Drive Auto-Folder Creation', 'On creating a new mobility record, automatically create the correct Drive folder structure: /Year/Flow/LastName/[Docs, Finance, LA, Correspondence]', 'Medium complexity / significant coordinator time savings'],
        ['Budget Burn Rate Live Dashboard', 'Real-time daily burn rate per country. Red flag when projected year-end utilisation exceeds 95% (over) or falls below 70% (under-utilisation penalty risk).', 'Medium complexity / critical for financial management'],
      ], ['Feature', 'Description', 'Complexity / Value'], [2200, 4600, 2560]),
      ...sp(1),
      h2('16.2 Medium Priority'),
      bl('Partner University Annual Review Module: structured review form sent to partner IROs, responses tracked, partnership health score calculated'),
      bl('Visa Requirements Tracker: automated checklist of visa requirements by nationality x destination country, linked to embassy websites'),
      bl('Learning Agreement Version Comparison: visual diff between LA versions showing exactly what changed, with tracked changes interface'),
      bl('EU Survey Completion Auto-Chase: system detects when survey should be completed (post-mobility), sends survey link, tracks completion with escalating reminders'),
      bl('Multi-Currency Informational Display: show grants in EUR with live exchange rate display for informational purposes (BWP, ZMW, UAH, etc.)'),
      bl('Mobility Alumni Opt-In Network: post-completion opt-in for alumni to share experiences with future outgoing students to the same university'),
      ...sp(1),
      h2('16.3 Nice to Have'),
      bl('WhatsApp notification integration for participants in countries where email reliability is low (Nigeria, Zambia, Botswana)'),
      bl('Mobile PWA with offline capability: coordinators can update document status without internet, syncs when connected'),
      bl('Digital signature integration: DocuSign or SignNow for Learning Agreements and Grant Agreements — eliminates physical paper signing'),
      bl('Photo directory of incoming participants: helps accommodation and reception staff identify students on arrival'),
      pageBreak(),

      // 17. ARCHITECTURE
      h1('17. Recommended Technical Architecture'),
      h2('17.1 Technology Stack'),
      infoBox([
        ['Frontend Framework', 'Next.js 14 (App Router) with TypeScript — SSR, excellent SEO for public portal, API routes'],
        ['UI Components', 'Tailwind CSS v3 + shadcn/ui — utility-first, accessible, design system consistent with existing portal'],
        ['State Management', 'Zustand (client) + TanStack Query (server state, caching, optimistic updates)'],
        ['Charts', 'Recharts (dashboards) + Leaflet.js (public portal map) + D3.js (complex custom visualisations)'],
        ['Backend Framework', 'Node.js + Fastify (REST API) or tRPC (type-safe end-to-end with Next.js)'],
        ['Authentication', 'NextAuth.js v5 with JWT strategy + SAML2 adapter for STU SSO integration'],
        ['Database', 'PostgreSQL 16 via Prisma ORM — type-safe migrations, excellent Next.js integration'],
        ['File Storage', 'AWS S3 or Supabase Storage — documents stored with signed URLs, virus-scanned before storage'],
        ['Email', 'Resend.com with React Email templates — transactional emails with delivery tracking'],
        ['Background Jobs', 'BullMQ (Redis-backed) — notification scheduler, reminder jobs, report generation queue'],
        ['Caching', 'Redis (Upstash for serverless) — API response caching, session storage, job queues'],
        ['Deployment', 'Vercel (Next.js frontend) + Railway or Render (Fastify API) + Supabase (PostgreSQL + Storage)'],
        ['Monitoring', 'Sentry (errors + performance) + PostHog (product analytics) + Uptime Robot (availability)'],
        ['Security', 'Helmet.js + CORS + rate limiting (Fastify Rate Limit) + automated Dependabot dependency updates'],
      ]),
      ...sp(1),
      h2('17.2 Security Architecture'),
      bl('All PII encrypted at rest using AES-256: passport numbers, phone numbers, addresses, IBANs'),
      bl('TLS 1.3 enforced for all data in transit; HSTS with 1-year max-age and includeSubDomains'),
      bl('API rate limiting: 100 requests/minute per authenticated user, 20/minute for authentication endpoints'),
      bl('Input sanitisation: all user inputs sanitised against XSS and SQL injection at API middleware layer'),
      bl('File upload scanning: ClamAV antivirus scan before any uploaded document is committed to storage'),
      bl('GDPR Article 17 compliance: data deletion workflow with 30-day grace period and audit trail'),
      bl('Row-level security in PostgreSQL: database-enforced scoping — users can only query data within their role scope'),
      bl('CSP headers: Content Security Policy preventing XSS, clickjacking, and data injection attacks'),
      pageBreak(),

      // 18. SAAS
      h1('18. SaaS Expansion Plan'),
      h2('18.1 Multi-Tenancy Architecture'),
      p('The SaaS version uses a schema-per-tenant approach in PostgreSQL: each university client gets an isolated database schema (e.g., "tenant_stu_bratislava", "tenant_tu_berlin") with a shared public schema for rate tables, countries, and reference data. This provides complete data isolation, independent backup capability, and per-tenant migration management.'),
      ...sp(1),
      h2('18.2 University Onboarding Flow'),
      nb('University administrator signs up → selects subscription plan → email verification'),
      nb('Automated tenant provisioning: new PostgreSQL schema created, default rate tables copied from public schema'),
      nb('IRO admin account created; onboarding wizard launched'),
      nb('Wizard: upload logo, set academic year, configure faculties and coordinator accounts'),
      nb('Data import: CSV/Excel import wizard with column mapping matching existing spreadsheet structure'),
      nb('Google Drive integration: connect institutional Google Workspace account via OAuth2'),
      nb('SSO configuration: connect to university identity provider (optional, guided setup)'),
      nb('Go-live: system fully operational; existing coordinator onboarding training (2-hour session)'),
      ...sp(1),
      h2('18.3 Subscription Plans'),
      threeCol([
        ['Starter', 'EUR 99/month', 'Up to 50 mobilities/year, 3 coordinators, 1 project type, basic reports, email support'],
        ['Professional', 'EUR 299/month', 'Up to 250 mobilities/year, unlimited coordinators, 5 project types, advanced analytics, priority support, Google Drive, AI assistant 50 queries/month'],
        ['University', 'EUR 799/month', 'Unlimited mobilities, all project types (KA171/KA131/KA107), full AI features, custom branding, SSO, SLA 99.9%, dedicated support manager'],
        ['Enterprise', 'Custom pricing', 'Multi-campus, white-label option, on-premise deployment, custom integrations, data residency guarantees, GDPR DPA, dedicated infrastructure'],
      ], ['Plan', 'Price', 'Included Features'], [1800, 1400, 6160]),
      pageBreak(),

      // 19. ROADMAP
      h1('19. Development Roadmap'),
      h2('Phase 1 — MVP (Months 1-4): Core Data Management'),
      p('Goal: Replace Google Sheets with a functional, secure web application for STU\'s IRO team.'),
      bl('Authentication system: email login, MFA for admin roles, session management'),
      bl('PostgreSQL database with full schema based on Section 9, Prisma migrations'),
      bl('Student and staff management with complete profile forms matching all PDF fields'),
      bl('Document tracking module with real-time status updates and file upload'),
      bl('Basic dashboard with Chart.js KPI cards powered by real database queries'),
      bl('Excel import wizard exactly matching current spreadsheet column structure'),
      bl('Export to XLSX/CSV for all entity tables'),
      bl('Email notification system (Resend API) for document reminders'),
      bl('Google Drive folder auto-creation per mobility (Drive API)'),
      bl('Deployment: Vercel + Railway + Supabase (completely free tier for MVP)'),
      p('Estimated effort: 2 developers x 4 months = 640 developer-hours', { italic: true, color: C.gray }),
      ...sp(1),
      h2('Phase 2 — Internal System (Months 5-8): Full Feature Set'),
      p('Goal: Complete IRO system replacing all current spreadsheet workflows.'),
      bl('Budget management module with dynamic grant calculation engine and rate tables editor'),
      bl('Partner university and partner manager modules with IIA tracking'),
      bl('Calendar module with iCal export and event categorisation'),
      bl('Task management Kanban board with assignment and deadline tracking'),
      bl('All 12 pre-built report types with PDF generation'),
      bl('Contact participant email sending via Resend API with template system'),
      bl('Notification centre with configurable rules, email digest, and real-time in-app alerts'),
      bl('Cancelled mobilities management with GA budget impact calculation'),
      bl('Full audit log viewer with filtering and export for EC compliance'),
      bl('Complete data migration from existing Google Sheets (all historical records)'),
      p('Estimated effort: 2 developers x 4 months = 640 developer-hours', { italic: true, color: C.gray }),
      ...sp(1),
      h2('Phase 3 — Multi-Faculty Platform (Months 9-12): Scale & AI'),
      p('Goal: Expand to all STU faculties with faculty-specific coordination and AI features.'),
      bl('Faculty coordinator role with faculty-scoped dashboards and approval workflows'),
      bl('Student public portal (interactive map, university directory, anonymised statistics)'),
      bl('AI assistant integration with live database context (Claude API)'),
      bl('Passport/insurance OCR document parsing'),
      bl('Budget forecasting and anomaly detection'),
      bl('Mobile PWA with offline document status updates'),
      bl('Advanced analytics with custom report builder'),
      p('Estimated effort: 3 developers x 4 months = 960 developer-hours', { italic: true, color: C.gray }),
      ...sp(1),
      h2('Phase 4 — SaaS Product (Year 2)'),
      p('Goal: Launch as a commercial SaaS product targeting Slovak and Central European universities.'),
      bl('Multi-tenancy architecture (schema-per-tenant PostgreSQL)'),
      bl('Self-service university onboarding and subscription management (Stripe billing)'),
      bl('KA131 (European Exchange) module alongside KA171 (International Credit Mobility)'),
      bl('Custom branding / white-label per tenant, SSO integration wizard'),
      bl('Marketing website, documentation portal, and support knowledge base'),
      bl('First paying clients: 5-10 Slovak universities (UTB, UKF, UPJS, TU Kosice)'),
      p('Estimated effort: 4 developers x 6 months = 1,920 developer-hours', { italic: true, color: C.gray }),
      ...sp(1),
      h2('Phase 5 — International Ecosystem (Year 3-4)'),
      bl('Erasmus Without Paper (EWP) API integration for direct university-to-university data exchange'),
      bl('EMREX student data portability standard integration'),
      bl('Automatic EU Survey API data submission to European Commission'),
      bl('Multi-language interface: Slovak, Czech, Ukrainian, German, French, Spanish, Polish'),
      bl('Marketplace: connect universities directly with partner IROs for new IIA agreements'),
      bl('KA2 (Strategic Partnerships), Erasmus Mundus Joint Master, and European Solidarity Corps modules'),
      bl('Target: 50+ universities, EUR 500k+ ARR, potential acquisition by education sector ERP vendor'),
      pageBreak(),

      // 20. FINAL EVALUATION
      h1('20. Final Evaluation'),
      h2('20.1 Current Maturity Assessment'),
      scoreTable([
        ['Frontend Design & UX', '8.5 / 10', 'Professional, modern, well-organised. Minor gaps in mobile responsiveness and advanced table features.', C.lightGreen],
        ['Functional Coverage (UI)', '7.0 / 10', 'All major pages exist with correct entity structure. Backend integration absent throughout.', C.lightBlue],
        ['Backend Completeness', '0 / 10', 'No backend exists. All data generated in-browser. Zero data persistence across sessions.', C.lightRed],
        ['PDF Data Alignment', '5.0 / 10', 'Major entities present but OS budget, CRZ docs, green travel, and cancelled mobilities archive are missing.', C.lightOrange],
        ['Security & GDPR Compliance', '0 / 10', 'No authentication, no data encryption, client-side PII. GDPR non-compliant by design.', C.lightRed],
        ['Scalability Architecture', '2.0 / 10', 'Single HTML file with client-side JavaScript cannot scale to real production usage.', C.lightRed],
        ['Enterprise Readiness', '15%', 'Strong visual foundation; complete backend engineering required to become production-viable.', C.lightRed],
        ['Estimated Completion to Production', '6-9 months', '~1,280-1,920 developer-hours remaining for Phase 1+2. 2 senior full-stack developers recommended.', C.lightOrange],
      ]),
      ...sp(1),
      h2('20.2 Most Critical Missing Items (Priority Order)'),
      nb('Secure authentication system (NextAuth.js) — ABSOLUTE BLOCKER for any real usage'),
      nb('PostgreSQL database with Prisma schema matching all spreadsheet entities exactly'),
      nb('REST API layer (Fastify/Express) connecting frontend forms to the database'),
      nb('Real Excel import engine with validation and field mapping matching current spreadsheet'),
      nb('OS (Organisational Support) budget tracking — EUR 500/mobility, legally required by EC'),
      nb('Grant calculation engine with dynamic rate tables (currently hardcoded or absent)'),
      nb('Green travel incentive flag and EUR 50 reimbursement workflow'),
      nb('CRZ document type and tracking (Slovak public contracts register — mandatory by law)'),
      nb('Cancelled mobilities archive with full data preservation and GA budget impact'),
      nb('PDF report generation for Erasmus+ EC submission (Mobility Tool+ compatible format)'),
      ...sp(1),
      h2('20.3 Recommended Immediate Next Steps'),
      bl('WEEK 1-2: Set up development environment — Next.js 14 + PostgreSQL + Prisma + NextAuth.js on local Docker'),
      bl('WEEK 3-4: Implement complete database schema (Section 9 of this document) with Prisma migrations'),
      bl('WEEK 5-8: Build authentication system + coordinator dashboard connected to real database queries'),
      bl('WEEK 9-12: Migrate existing HTML portal components to Next.js with real API calls replacing client-side data'),
      bl('MONTH 4: Import current Google Sheets data using the import wizard for user acceptance testing with real data'),
      bl('MONTH 5: Pilot with STU IRO team (Lucia + Tereza coordinators) — gather structured feedback and iterate'),
      bl('MONTH 6: Production launch for STU internal use — deprecate Google Sheets for active project cycle'),
      ...sp(1),
      h2('20.4 Strategic Conclusion'),
      p('The generated portal represents exceptional design and UX work at the frontend level. The visual quality, component library, and interface structure are genuinely production-grade and would take considerable time to reproduce from scratch. This is a strong and valuable foundation.'),
      p('The recommended path forward is to elevate, not rebuild: connect the existing UI to a properly engineered backend using the architecture described in this document. The primary investment should be in the data layer (PostgreSQL + Prisma), API layer (Fastify REST), and security layer (NextAuth.js + RBAC). The frontend requires targeted enhancements for PDF-aligned fields rather than a wholesale reconstruction.'),
      p('Given STU\'s real-world operational requirements (14 partner universities, 100+ mobilities/year, 4 active coordinators, legal compliance obligations), a fully functional production system can be realistically delivered within 6 months by a 2-person senior development team. The commercial SaaS opportunity is genuine and underserved — no purpose-built Erasmus+ ICM management system currently serves the Slovak or Central European university market, and the 4,000+ Erasmus+ participating universities across Europe represent a significant addressable opportunity.'),
      ...sp(2),
      divider(C.erasmusBlue),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 320, after: 160 }, children: [new TextRun({ text: 'Erasmus+ Management Portal — STU Bratislava', bold: true, size: 22, color: C.erasmusBlue, font: 'Arial' })] }),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 80 }, children: [new TextRun({ text: 'Strategic Analysis & Roadmap  |  Version 1.0  |  Confidential — Internal Use Only', size: 16, color: C.gray, font: 'Arial', italics: true })] }),
      new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'Project Reference: 2023-1-SK01-KA171-HED-000148295', size: 16, color: C.gray, font: 'Arial' })] }),
    ]
  }]
});

Packer.toBuffer(doc).then(buffer => {
  fs.writeFileSync('/mnt/user-data/outputs/Erasmus_Portal_Strategic_Analysis.docx', buffer);
  console.log('SUCCESS');
}).catch(err => {
  console.error('ERROR:', err.message);
  process.exit(1);
});